---
apiVersion: keycloak.m.crossplane.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: cluster-keycloak-provider-config
spec:
  credentials:
    source: Secret
    secretRef:
      name: keycloak-credentials
      key: credentials
      namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: default
  labels:
    type: provider-credentials
type: Opaque
stringData:
  credentials: |
    {
      "client_id":"admin-cli",
      "username": "admin",
      "password": "admin",
      "url": "http://keycloak-keycloakx-http.default.svc.cluster.local",
      "base_path": "/auth",
      "realm": "master"
    }
