---
apiVersion: keycloak.m.crossplane.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: cluster-keycloak-provider-config
spec:
  credentials:
    source: Secret
    secretRef:
      name: keycloak-credentials
      key: credentials
      namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: default
  labels:
    type: provider-credentials
type: Opaque
stringData:
  credentials: |
    {
      "client_id":"admin-cli",
      "username": "crossplane-admin",
      "password": "w8UV33RkBhEA6c+AaFoOOTYKGp3cnkQD",
      "url": "http://keycloak-service.keycloak.svc.cluster.local:8080",
      "realm": "master"
    }
