apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane

resources:
  - kustomize-resources/namespace.yaml
  - kustomize-resources/providers.yaml
  # - kustomize-resources/deployment-runtime-config.yaml
  # - kustomize-resources/keycloak-providerConfig-namespaced.yaml

helmCharts:
  - name: crossplane
    releaseName: crossplane
    namespace: crossplane
    repo: https://charts.crossplane.io/stable
    version: "v2.0.2"
